{{ config(
    materialized = 'table',
    tags = ['bronze', 'minuteintensitieswide', 'br'],
    description = 'Minute-level intensity data in wide format from Fitbit merged April dataset with timestamps standardized to YYYY-MM-DD HH24:MI:SS format.'
) }}

SELECT
    {{ cast_col('Id', 'number') }},
    {{ cast_timestamp('ActivityHour') }},
    {{ cast_col('Intensity00', 'number') }},
    {{ cast_col('Intensity01', 'number') }},
    {{ cast_col('Intensity02', 'number') }},
    {{ cast_col('Intensity03', 'number') }},
    {{ cast_col('Intensity04', 'number') }},
    {{ cast_col('Intensity05', 'number') }},
    {{ cast_col('Intensity06', 'number') }},
    {{ cast_col('Intensity07', 'number') }},
    {{ cast_col('Intensity08', 'number') }},
    {{ cast_col('Intensity09', 'number') }},
    {{ cast_col('Intensity10', 'number') }},
    {{ cast_col('Intensity11', 'number') }},
    {{ cast_col('Intensity12', 'number') }},
    {{ cast_col('Intensity13', 'number') }},
    {{ cast_col('Intensity14', 'number') }},
    {{ cast_col('Intensity15', 'number') }},
    {{ cast_col('Intensity16', 'number') }},
    {{ cast_col('Intensity17', 'number') }},
    {{ cast_col('Intensity18', 'number') }},
    {{ cast_col('Intensity19', 'number') }},
    {{ cast_col('Intensity20', 'number') }},
    {{ cast_col('Intensity21', 'number') }},
    {{ cast_col('Intensity22', 'number') }},
    {{ cast_col('Intensity23', 'number') }},
    {{ cast_col('Intensity24', 'number') }},
    {{ cast_col('Intensity25', 'number') }},
    {{ cast_col('Intensity26', 'number') }},
    {{ cast_col('Intensity27', 'number') }},
    {{ cast_col('Intensity28', 'number') }},
    {{ cast_col('Intensity29', 'number') }},
    {{ cast_col('Intensity30', 'number') }},
    {{ cast_col('Intensity31', 'number') }},
    {{ cast_col('Intensity32', 'number') }},
    {{ cast_col('Intensity33', 'number') }},
    {{ cast_col('Intensity34', 'number') }},
    {{ cast_col('Intensity35', 'number') }},
    {{ cast_col('Intensity36', 'number') }},
    {{ cast_col('Intensity37', 'number') }},
    {{ cast_col('Intensity38', 'number') }},
    {{ cast_col('Intensity39', 'number') }},
    {{ cast_col('Intensity40', 'number') }},
    {{ cast_col('Intensity41', 'number') }},
    {{ cast_col('Intensity42', 'number') }},
    {{ cast_col('Intensity43', 'number') }},
    {{ cast_col('Intensity44', 'number') }},
    {{ cast_col('Intensity45', 'number') }},
    {{ cast_col('Intensity46', 'number') }},
    {{ cast_col('Intensity47', 'number') }},
    {{ cast_col('Intensity48', 'number') }},
    {{ cast_col('Intensity49', 'number') }},
    {{ cast_col('Intensity50', 'number') }},
    {{ cast_col('Intensity51', 'number') }},
    {{ cast_col('Intensity52', 'number') }},
    {{ cast_col('Intensity53', 'number') }},
    {{ cast_col('Intensity54', 'number') }},
    {{ cast_col('Intensity55', 'number') }},
    {{ cast_col('Intensity56', 'number') }},
    {{ cast_col('Intensity57', 'number') }},
    {{ cast_col('Intensity58', 'number') }},
    {{ cast_col('Intensity59', 'number') }}
FROM {{ source('RAW_LAYER', 'minuteintensitieswide_merged_4_12') }}
